# Run tests against supported Node versions

version: 2.1

orbs:
  win: circleci/windows@4.1.1
  node: circleci/node@5.0.2

executors:
  node18:
    docker:
      - image: cimg/node:18.0.0 # Latest 18.x
    working_directory: ~/workspace
  node16:
    docker:
      - image: cimg/node:16.14.2 # Latest 16.x
    working_directory: ~/workspace

jobs:
  test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  test_win:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Install Node.js
          # 16.3.2 is possibly the newest Node 16.x version that's compatible
          # with nvm for windows:
          # See <https://stackoverflow.com/questions/70958371/unexpected-token-when-trying-to-run-npm-install>.
          command: nvm install 16.13.2 && nvm use 16.13.2
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - test:
          matrix:
            parameters:
              executor:
                - node18
                - node16
      - test_win
  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 10 * * *"
          filters:
            branches:
               only:
                 - main
