# Run tests against supported Node versions

version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  node16:
    docker:
      - image: cimg/node:16.1.0
    working_directory: ~/workspace
  node14_latest:
    docker:
      - image: circleci/node:14
    working_directory: ~/workspace
  node14_8:
    docker:
      - image: circleci/node:14.8
    working_directory: ~/workspace
  node14_7:
    docker:
      - image: circleci/node:14.7
    working_directory: ~/workspace
  node12_latest:
    docker:
    - image: circleci/node:12
    working_directory: ~/workspace
  node12_0:
    docker:
    - image: circleci/node:12.0
    working_directory: ~/workspace
  node12_17:
    docker:
    - image: circleci/node:12.17
    working_directory: ~/workspace
  node12_16:
    docker:
    - image: circleci/node:12.16
    working_directory: ~/workspace
  node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace

jobs:
  test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - test:
          matrix:
            parameters:
              executor:
                - node16
                - node14_latest
                - node14_8 # first with top level await in ES modules.
                - node14_7
                - node12_latest
                - node12_17 # first with dynamic import() of commonjs modules
                - node12_16
                - node12_0
                - node10
  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 10 * * *"
          filters:
            branches:
               only:
                 - main
                 - "3.99"
                 - "4.0"
